DELETE https://localhost:7488/api/users/2
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJuYmYiOjE3MjA3MTM3NTgsImV4cCI6MTcyMTMxODU1OCwiaWF0IjoxNzIwNzEzNzU4fQ.WExyCkUHOQOboKe5dNu-F718FRf2DT60D73bZZGK0vY
